services:
  filez-demo-nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: filez-demo-nodejs
    container_name: filez-demo-nodejs
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    env_file:
      - .env
    volumes:
      - ./docker-data/data:/app/data
      - ./docker-data/uploads:/app/uploads
      - ./docker-data/logs:/app/logs
    restart: unless-stopped

